version: '3.9'

services:
    postgres-db-app:
        container_name: estacionamento-postgres-db
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "estacionamento"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    postgres-db-sonarqube:
        image: postgres:latest
        container_name: sonarqube-postgres-db
        environment:
            POSTGRES_USER: "sonaruser"
            POSTGRES_PASSWORD: "sonarpass"
            POSTGRES_DB: "sonarqube"
        volumes:
            - sonarqube-postgres-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"

    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        depends_on:
            - postgres-db-sonarqube
        ports:
            - "9000:9000"
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://postgres-db-sonarqube:5432/sonarqube
            SONAR_JDBC_USERNAME: "sonaruser"
            SONAR_JDBC_PASSWORD: "sonarpass"
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
    postgres-data:
    sonarqube-postgres-data:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
