name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checkstyle:
    name: Checkstyle Java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run Checkstyle
        run: ./mvnw clean verify

  maven-test:
    name: Testes Unitários
    runs-on: ubuntu-latest
    needs: checkstyle
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run Tests & JaCoCo
        run: ./mvnw clean test jacoco:report

  sonarcloud:
    name: Sonar Cloud Analysis
    runs-on: ubuntu-latest
    needs: maven-test
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Sonar Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=thiagoDimon_sistema-gestao-estacionamento
            -Dsonar.organization=thiagodimon
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
